import {
  pgTable,
  serial,
  varchar,
  text,
  boolean,
  integer,
  numeric,
  timestamp,
} from "drizzle-orm/pg-core";

export const insuranceAgencies = pgTable("insurance_agencies", {
  id: serial("id").primaryKey(),
  agencyName: text("agency_name").notNull(),
  ownerPrincipal: text("owner_principal"),
  address: text("address"),
  city: text("city"),
  state: varchar("state", { length: 5 }),
  zip: varchar("zip", { length: 15 }),
  county: text("county"),
  phone: varchar("phone", { length: 20 }),
  email: text("email"),
  licenseNumber: varchar("license_number", { length: 30 }),
  npn: varchar("npn", { length: 20 }),
  licenseType: text("license_type"),
  linesOfAuthority: text("lines_of_authority"),
  status: varchar("status", { length: 20 }),
  sourceState: varchar("source_state", { length: 5 }),
  source: text("source"),
  websiteUrl: text("website_url"),
  linkedinCompanyUrl: text("linkedin_company_url"),
  linkedinPersonalUrl: text("linkedin_personal_url"),
  googleBusinessExists: boolean("google_business_exists"),
  googleBusinessUrl: text("google_business_url"),
  googleRating: numeric("google_rating", { precision: 2, scale: 1 }),
  googleReviewCount: integer("google_review_count"),
  googleBusinessHours: text("google_business_hours"),
  facebookExists: boolean("facebook_exists"),
  facebookUrl: text("facebook_url"),
  instagramExists: boolean("instagram_exists"),
  instagramUrl: text("instagram_url"),
  yelpExists: boolean("yelp_exists"),
  yelpRating: numeric("yelp_rating", { precision: 2, scale: 1 }),
  yelpReviewCount: integer("yelp_review_count"),
  employeeCount: integer("employee_count"),
  yearsInBusiness: integer("years_in_business"),
  agencySummary: text("agency_summary"),
  digitalPresenceScore: varchar("digital_presence_score", { length: 20 }),
  gtmSignals: text("gtm_signals").array(),
  enrichedAt: timestamp("enriched_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export type Agency = typeof insuranceAgencies.$inferSelect;
